// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNwlEMj4wFV69BgfpmjjxuiI1sTSLsaMg',
    appId: '1:1015175199599:web:867622be11e7621c8b069a',
    messagingSenderId: '1015175199599',
    projectId: 'mohra-door-lock',
    authDomain: 'mohra-door-lock.firebaseapp.com',
    storageBucket: 'mohra-door-lock.appspot.com',
    measurementId: 'G-8LQHXMRTF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVXoKYYkl8sh3-4NeFo7jxtkb4t8YQFQY',
    appId: '1:1015175199599:android:c69f2dae48500cfd8b069a',
    messagingSenderId: '1015175199599',
    projectId: 'mohra-door-lock',
    storageBucket: 'mohra-door-lock.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCouGvMFlmoCOWkkXkw2evZ_nze138guHc',
    appId: '1:1015175199599:ios:1233f5db500434c58b069a',
    messagingSenderId: '1015175199599',
    projectId: 'mohra-door-lock',
    storageBucket: 'mohra-door-lock.appspot.com',
    iosBundleId: 'com.example.doorlock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCouGvMFlmoCOWkkXkw2evZ_nze138guHc',
    appId: '1:1015175199599:ios:1233f5db500434c58b069a',
    messagingSenderId: '1015175199599',
    projectId: 'mohra-door-lock',
    storageBucket: 'mohra-door-lock.appspot.com',
    iosBundleId: 'com.example.doorlock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNwlEMj4wFV69BgfpmjjxuiI1sTSLsaMg',
    appId: '1:1015175199599:web:54db2604550c7cc28b069a',
    messagingSenderId: '1015175199599',
    projectId: 'mohra-door-lock',
    authDomain: 'mohra-door-lock.firebaseapp.com',
    storageBucket: 'mohra-door-lock.appspot.com',
    measurementId: 'G-LVD49XMT2E',
  );
}
